### ISSUE TITLE
Update to WLED 0.13.0-b4

### ISSUE THREAD

**Issue by maltyjava** [awawa-dev/WLED#4]
Hi,

Would it be possible to get an update of HyperSerialWLED from 0.12 to the latest 0.13.0-b4?

I've used the old version for a long time now, but I have since updated all my other non ambilight WLEDs to the latest version, so that I can use the new sync groups without having to set different ports for each group. Unfortunately that means I can't use old versions of WLED as part of these groups. I also need the ambilight to be controlled through WLED for LedFX usage, otherwise I'd use HyperSerial.

Also I would just use adalight through WLED, but there are strange flickering issues that aren't present with HyperSerialWLED.

Thanks for all your work!

**Comment by awawa-dev** [comment]
Hi
You mean that? https://github.com/awawa-dev/HyperSerialWLED/releases/tag/v4.0.0.0beta 😉

**Comment by maltyjava** [comment]
Exactly like that!! Haha my bad. Cheers :)
