### ISSUE TITLE
Document that the white channel is not used

### ISSUE THREAD

**Issue by NickHu** [awawa-dev/WLED#5]
I'm fairly sure that the line of code which sets the signal for any LED is here: https://github.com/awawa-dev/HyperSerialWLED/blob/24d825fef57e7d6a8337eca5d3e4a9967b0c7cd6/wled00/wled_serial.cpp#L105

If I understood correctly, this means that the white channel is always unused on RGBW LED strips, which is in contrast to e.g. https://github.com/awawa-dev/HyperSerialEsp8266.

As far as I'm aware, even though both WLED and HyperHDR (and forks) individually have support for RGBW, it's not possible to use the white channel when using both. See https://github.com/hyperion-project/hyperion.ng/issues/446. I guess this itself isn't an issue per say, as HyperSerialEsp8266 is preferred over HyperSerialWLED anyway, but it should probably be documented.

**Comment by awawa-dev** [comment]
Hi
It's implemented the same as in WLED:
https://github.com/Aircoookie/WLED/blob/f922268af7fba7b035d5e8c1ca707ecce13ffd3f/wled00/wled_serial.cpp#L174
If they change it then I will consider to implement it also. As you noticed I consider WLED useful only as a very helpful tool for testing the setup, not necessarily as the final driver so won't extend the documentation about how it's implemented in WLED (but if I were you i would first make sure setRealtimePixel somehow doesn't update it to RGBW as this offers a WLED interface if enabled...you can ask  WLED developers as it is beyond the scope of this fork)  
Regards
Awawa
