### ISSUE TITLE
Random flashing when using HyperSerialWLED. HyperSerialESP32 works great.

### ISSUE THREAD

**Issue by AZDane** [awawa-dev/WLED#7]
### What happened?

Random flashing when using HyperSerialWLED. HyperSerialESP32 works great.

### To Reproduce Bug

Simple ambilight tests works fine, but when playing back movies I get random flashes that are not present when using HyperSerialESP32.

### Expected Behavior

Hopefully the same result using HyperSerialWLED as I get when using HyperSerialESP32 which is awesome.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awawa-dev** [comment]
Not a HyperSerialWLED issue, need to be fixed in the upstream first. Discussed here: https://github.com/awawa-dev/HyperHDR/discussions/649
